version: 1

formatters:
  base_formatter:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  stdout_handler:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
    formatter: base_formatter

root:
  level: INFO
  handlers: [stdout_handler]
